//%attributes = {}

_ga_createMoreDataFields

__import_quote_param
__import_lead_param
__import_data_lists
__import_data_customer
//__import_data_employees
__import_teams
__import_purchaseOrders
//__import_data_archivedJobs
__import_data_equipment
__import_country
__import_data_CIP

__import_data_avl_aml
__import_data_quote
__import_data_audit
__import_data_managementReview
__import_data_buyingOrders
__import_data_chartOfAccount
__import_data_assetList
__import_data_creditMemo
__import_data_deposit
__import_data_journalEntry
__import_data_check
__import_data_billPayment
__import_data_supplierCredit
__import_data_expenseTransaction
__import_data_financialReport

_ga_fillBarcodeDataField

ALERT:C41("Import done")

