//cs.panel_lead.me.btnDatePickerCreate(Form.current_interaction; "stmpFollowUp"; True; 1)
cs:C1710.panel_lead.me.btnDatePicker(Form:C1466.current_interaction; "followUPDate")
Form:C1466.current_interaction.save()
Form:C1466.current_interaction.reload()
cs:C1710.panel_lead.me._activate_save_cancel_button()
